# Generated by Django 3.1 on 2020-09-25 18:40

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(choices=[('1A', 'Primero A'), ('1B', 'Primero B'), ('1C', 'Primero C'), ('2A', 'Segundo A'), ('2B', 'Segundo B'), ('2C', 'Segundo C'), ('3A', 'Tercero A'), ('3B', 'Tercero B'), ('3C', 'Tercero C'), ('4A', 'Cuarto A'), ('4B', 'Cuarto B'), ('4C', 'Cuarto C'), ('5A', 'Quinto A'), ('5B', 'Quinto B'), ('5C', 'Quinto C'), ('6A', 'Sexto A'), ('6B', 'Sexto B'), ('6C', 'Sexto C'), ('7A', 'Septimo A'), ('7B', 'Septimo B'), ('7C', 'Septimo C')], max_length=2)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('dni', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Directivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PadreTutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('delegado', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Preceptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('dni', models.CharField(max_length=30)),
                ('curso', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1A', 'Primero A'), ('1B', 'Primero B'), ('1C', 'Primero C'), ('2A', 'Segundo A'), ('2B', 'Segundo B'), ('2C', 'Segundo C'), ('3A', 'Tercero A'), ('3B', 'Tercero B'), ('3C', 'Tercero C'), ('4A', 'Cuarto A'), ('4B', 'Cuarto B'), ('4C', 'Cuarto C'), ('5A', 'Quinto A'), ('5B', 'Quinto B'), ('5C', 'Quinto C'), ('6A', 'Sexto A'), ('6B', 'Sexto B'), ('6C', 'Sexto C'), ('7A', 'Septimo A'), ('7B', 'Septimo B'), ('7C', 'Septimo C')], max_length=62, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudReunion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo', models.TextField()),
                ('padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.padretutor')),
            ],
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('tipo_form', models.CharField(choices=[('F1', 'Formulario 1'), ('F2', 'Formulario 2'), ('F3', 'Formulario 3')], default='F1', max_length=2)),
                ('dias', models.CharField(max_length=45, null=True)),
                ('fecha', models.DateField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha', models.DateField()),
                ('mensaje', models.TextField()),
                ('curso', multiselectfield.db.fields.MultiSelectField(choices=[('1A', 'Primero A'), ('1B', 'Primero B'), ('1C', 'Primero C'), ('2A', 'Segundo A'), ('2B', 'Segundo B'), ('2C', 'Segundo C'), ('3A', 'Tercero A'), ('3B', 'Tercero B'), ('3C', 'Tercero C'), ('4A', 'Cuarto A'), ('4B', 'Cuarto B'), ('4C', 'Cuarto C'), ('5A', 'Quinto A'), ('5B', 'Quinto B'), ('5C', 'Quinto C'), ('6A', 'Sexto A'), ('6B', 'Sexto B'), ('6C', 'Sexto C'), ('7A', 'Septimo A'), ('7B', 'Septimo B'), ('7C', 'Septimo C')], max_length=62)),
                ('directivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.directivo')),
            ],
        ),
    ]
