# Generated by Django 3.1 on 2020-09-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directivo',
            name='cargo',
            field=models.CharField(choices=[('DG', 'Director General'), ('DA', 'Director Academico'), ('VD', 'Vicedirector')], default='VD', max_length=2),
        ),
    ]
