# Generated by Django 3.1 on 2020-10-19 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='alumno',
            new_name='tutor',
        ),
    ]
