# Generated by Django 3.1 on 2020-09-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicadociclo',
            name='titulo',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='comunicadocurso',
            name='titulo',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='comunicadogeneral',
            name='titulo',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
