# Generated by Django 3.1 on 2020-11-12 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201112_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_padre',
            field=models.BooleanField(default=False),
        ),
    ]
