# Generated by Django 3.1 on 2020-11-10 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20201019_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='padretutor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='padretutor',
            name='username',
        ),
        migrations.AddField(
            model_name='padretutor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
