# Generated by Django 3.1 on 2020-09-17 17:48

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200917_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='curso',
            field=models.CharField(choices=[('1A', 'Primero A'), ('1B', 'Primero B'), ('1C', 'Primero C'), ('2A', 'Segundo A'), ('2B', 'Segundo B'), ('2C', 'Segundo C'), ('3A', 'Tercero A'), ('3B', 'Tercero B'), ('3C', 'Tercero C'), ('4A', 'Cuarto A'), ('4B', 'Cuarto B'), ('4C', 'Cuarto C'), ('5A', 'Quinto A'), ('5B', 'Quinto B'), ('5C', 'Quinto C'), ('6A', 'Sexto A'), ('6B', 'Sexto B'), ('6C', 'Sexto C'), ('7A', 'Septimo A'), ('7B', 'Septimo B'), ('7C', 'Septimo C')], max_length=2),
        ),
        migrations.RemoveField(
            model_name='preceptor',
            name='curso',
        ),
        migrations.AddField(
            model_name='preceptor',
            name='curso',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1A', 'Primero A'), ('1B', 'Primero B'), ('1C', 'Primero C'), ('2A', 'Segundo A'), ('2B', 'Segundo B'), ('2C', 'Segundo C'), ('3A', 'Tercero A'), ('3B', 'Tercero B'), ('3C', 'Tercero C'), ('4A', 'Cuarto A'), ('4B', 'Cuarto B'), ('4C', 'Cuarto C'), ('5A', 'Quinto A'), ('5B', 'Quinto B'), ('5C', 'Quinto C'), ('6A', 'Sexto A'), ('6B', 'Sexto B'), ('6C', 'Sexto C'), ('7A', 'Septimo A'), ('7B', 'Septimo B'), ('7C', 'Septimo C')], max_length=62, null=True),
        ),
    ]
