# Generated by Django 3.1 on 2020-11-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customuser_is_padre'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='hora',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
