# Generated by Django 3.1 on 2020-11-22 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_formulario_hora'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComunicadoRecibido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comunicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.comunicado')),
                ('padre_tutor', models.ManyToManyField(null=True, to='app.PadreTutor')),
            ],
        ),
    ]
