# Generated by Django 3.1 on 2020-11-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201110_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='padretutor',
            name='rol',
            field=models.CharField(default='', max_length=30),
        ),
    ]
