# Generated by Django 3.1 on 2020-11-22 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_comunicadorecibido'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicadorecibido',
            name='recibido',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='comunicadorecibido',
            name='padre_tutor',
        ),
        migrations.AddField(
            model_name='comunicadorecibido',
            name='padre_tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.padretutor'),
        ),
    ]
